config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'bienvenido/index'
  resources :articulos do
  resources :comentarios
end
root 'bienvenido#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
     has_many :comentarios, dependent: :destroy 
      validates :titular, presence: true,
                    length: { minimum: 5 }
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :articulo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController

#http_basic_authenticate_with name: "dhh", password: "secreto", except: [:index, :show]
 

  def index
    @articulos = Articulo.all
  end
 
  def show
    @articulo = Articulo.find(params[:id])
  end
 
  def new
    @articulo = Articulo.new
  end
 
  def edit
    @articulo = Articulo.find(params[:id])
  end
 
  def create
    @articulo = Articulo.new(articulo_params)
 
    if @articulo.save
      redirect_to @articulo
    else
      render 'new'
    end
  end
 
  def update
    @articulo = Articulo.find(params[:id])
 
    if @articulo.update(articulo_params)
      redirect_to @articulo
    else
      render 'edit'
    end
  end
 
  def destroy
    @articulo = Articulo.find(params[:id])
    @articulo.destroy
 
    redirect_to articulos_path
  end
 
  private
    def articulo_params
      params.require(:articulo).permit(:titular, :contenido)
    end
end 

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  
  #http_basic_authenticate_with name: "dhh", password: "secreto", only: :destroy

  def create
    @articulo = Articulo.find(params[:articulo_id])
    @comentario = @articulo.comentarios.create(comentario_params)
    redirect_to articulo_path(@articulo)
  end
 
 def destroy
    @articulo = Articulo.find(params[:articulo_id])
   @comentario = @articulo.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to articulo_path(@articulo)
  end

def show
    @articulo = Articulo.find(params[:articulo_id])
   @comentario = @articulo.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to articulo_path(@articulo)
end


  private
    def comentario_params
      params.require(:comentario).permit(:comentarista, :contenido)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/articulos/_form.html.erb
<%= form_for @articulo do |f| %>
 
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@articulo.errors.count, "error") %> han impedido que el artículo sea grabado:
      </h2>
      <ul>
        <% @articulo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :titular %><br>
    <%= f.text_field :titular %>
  </p>
 
  <p>
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </p>
 
  <p>
    <%= f.submit 'Guardar Artículo' %>
  </p>
 
<% end %>

app/views/articulos/edit.html.erb
<h1>Editar el artículo</h1>
 
<%= render 'form' %>
 
<%= link_to 'Volver', articulos_path %>

app/views/articulos/index.html.erb
<h1>Mensajes de Amor  para Alix<3 <3 <3</h1>
 
<table>
  <tr>
    <th>Titular</th>
    <th>mensaje</th>
  </tr>
 
  <% @articulos.each do |articulo| %>
    <tr>
      <td><%= articulo.titular %></td>
      <td><%= articulo.contenido %></td>
      <td><%= link_to 'ver', articulo_path(articulo) %> </td>
      <td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
      <td><%= link_to 'Borrar', articulo_path(articulo),
              method: :delete,
              data: { confirm: '¿Estás seguro?' } %></td>
    </tr>
  <% end %>
</table>



<%= link_to 'Nuevo Artículo', new_articulo_path %>

app/views/articulos/new.html.erb
<h1>Nuevo Artículo</h1>
 
<%= render 'form' %>
 
<%= link_to 'Volver', articulos_path %>

app/views/articulos/show.html.erb
<p>
  <strong>Titular:</strong>
  <%= @articulo.titular %>
</p>
 
<p>
  <strong>Contenido:</strong>
  <%= @articulo.contenido %>
</p>
 
<h2>Comentarios</h2>
<%= render @articulo.comentarios %>
 
<h2>Añade un comentario:</h2>
<%= render 'comentarios/form' %>
 
<%= link_to 'Editar Artículo', edit_articulo_path(@articulo) %> |
<%= link_to 'Volver a Articulos', articulos_path %>

app/views/bienvenido/index.html.erb
<h1>Holi Alix, te amo att: Nestor</h1>



<% if current_user %>
    <%= link_to 'Ingresar a Nestor', controller: 'articulos' %>
<% else %>
    <h2>Inicia para poder darte besitos <3 <3 <3 </h2>
<% end %>

app/views/comentarios/_comentario.html.erb
<p>
  <strong>Comentarista:</strong>
  <%= comentario.comentarista %>
</p>
 
<p>
  <strong>Comentario:</strong>
  <%= comentario.contenido %>
</p>
 
<p>
  <%= link_to 'Borrar Comentario', [comentario.articulo, comentario],
               method: :delete,
               data: { confirm: '¿Estás seguro?' } %>
</p>  

app/views/comentarios/_form.html.erb
<%= form_for([@articulo, @articulo.comentarios.build]) do |f| %>
  <p>
    <%= f.label :comentarista %><br>
    <%= f.text_field :comentarista %>
  </p>
  <p>
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </p>
  <p>
    <%= f.submit 'Guardar Comentario' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>



<% if current_user %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to 'Login', new_user_session_path %>
<% end %>


<div class='logo'>
<%= image_tag "aa.jpg", width:'150px', :class => "style_image" %>
</div>


    <%= yield %>
  </body>
</html>